services:

  cmp-auth:
    build: .
    image: entityblackhawk/cmp-auth:latest
    networks:
      - network-auth
    environment:
        - MONGODB_HOST=db-auth:27017
    depends_on:
      - db-auth

  db-auth:
    image: mongo:latest
    networks:
      - network-auth
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_DATABASE: auth

networks:
    network-auth:
        driver: bridge